### ISSUE TITLE
Electerm同步的custom处该如何填写？

### ISSUE THREAD

**Issue by tedrx-hr** [electerm/electerm-sync-server-rust#1]
作者您好，想问一下，custom同步该如何设置？

其中API Url是什么，是http://xxx.xxx.xxx.xxx:7837/api/sync这样子吗？
然后JWT Secret则是.env里的那一串对吧？
User ID亦是在.env处设置？

照上述设置，提示token Invalid
![invalid_token](https://github.com/user-attachments/assets/04da782a-146b-4a13-9b3f-231e7edb91f7)
![process_success](https://github.com/user-attachments/assets/b91e6bf8-6e6f-40dc-bf4b-432109358650)

**Comment by zxdong262** [comment]
我试了http://127.0.0.1:7837/api/sync是可以的，都是跟.env一致就可以，是不是地址反向代理没有生效?

可以浏览器访问 http://xxx.xxx.xxx.xxx:7837/test 确认服务是否可用

**Comment by tedrx-hr** [comment]
我照您说的去做了一下，服务似乎是不可用的，服务器本地curl的话是显示404了？以及地址反向代理生效这一步是啥意思，不太懂，ai了一下也不知道怎么操作，非常抱歉🤦‍♂️
![屏幕截图 2024-11-17 095300](https://github.com/user-attachments/assets/706049b9-5415-4007-ae2a-f4e1bc4d48f0)
![屏幕截图 2024-11-17 095343](https://github.com/user-attachments/assets/5c9f551c-22e0-46aa-af1b-8ab2232287c6)
![屏幕截图 2024-11-17 100836](https://github.com/user-attachments/assets/ec8f3bc9-19ca-4cac-ac48-a570c4de51ad)
![屏幕截图 2024-11-17 101010](https://github.com/user-attachments/assets/8ea58c45-0bad-489b-8a2f-61ace3179c60)

**Comment by zxdong262** [comment]
如果按照默认的.env启动，监听的地址是127.0.0.1，只有本机能访问这个地址，如果想从互联网上其他机器访问，就需要使用例如nginx这种软件做反向代理，把外部访问转发到本地127.0.0.1, 或者直接.env里host设为本机ip，那么可以访问到这个ip的也可以访问

注意安全，如果是实际部署一个互联网上的服务，推荐绑定域名和开启https

**Comment by tedrx-hr** [comment]
嗷嗷好的好的OKK，谢谢您了，我去用nginx试一下，感谢答复啦
